/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edt5y6tacondeoro;

import edt5tacondeoro1.Articulo;
import edt5tacondeoro1.Bolso;
import edt5tacondeoro1.Complemento;
import edt5tacondeoro1.Zapato;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author usumaniana
 */
public class HacerPedido extends javax.swing.JDialog {
    private SistemaVP mipadre=null;
    DefaultListModel dlmArticulos=null;
    //hay que revisar si la ruta es la correcta
    public static final String URL="jdbc:mysql://localhost/tacondeoro";
    public static final String USERNAME="root";
    public static final String PASSWORD="toor";
    DefaultTableModel dtm_articulo;
    DefaultListModel dlm_carrito;
    /**
     * Creates new form HacerPedido
     */
    public HacerPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        cmb_tallaz.removeAllItems();
//        cmb_tallaz.addItem("36");
//        cmb_tallaz.addItem("38");
//        cmb_tallaz.addItem("36");
//        cmb_tallaz.addItem("39");
//        cmb_tallaz.addItem("40");
//        cmb_tallaz.addItem("41");
//        cmb_tallaz.addItem("42");
        dlm_carrito=new DefaultListModel();
        lst_carrito.setModel(dlm_carrito);
        dtm_articulo=new DefaultTableModel();
        dtm_articulo.addColumn("Nombre");
        dtm_articulo.addColumn("Descripcion");
        dtm_articulo.addColumn("Tipo");
        dtm_articulo.addColumn("Precio");
        //asignamos el modelo a la vista tabla
        tbl_articulos.setModel(dtm_articulo);
        try{
            DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        } catch (SQLException ex) {
            Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        mipadre=(SistemaVP)parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_añadircarrito = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_carrito = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_guardarpedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        etiqueta = new javax.swing.JLabel();
        btn_mostrarartiulos = new javax.swing.JButton();
        btn_actualizarcarrito = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spn_cantidad = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_articulos = new javax.swing.JTable();
        tf_talla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ARTICULOS:");

        btn_añadircarrito.setText("Añadir a carrito");
        btn_añadircarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadircarritoActionPerformed(evt);
            }
        });

        lst_carrito.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_carrito);

        jLabel2.setText("CARRITO:");

        btn_guardarpedido.setText("Guardar pedido");
        btn_guardarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarpedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad:");

        etiqueta.setText("imagen");

        btn_mostrarartiulos.setText("Mostar articulos");
        btn_mostrarartiulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarartiulosActionPerformed(evt);
            }
        });

        btn_actualizarcarrito.setText("Actualizar carrito");

        jLabel5.setText("Talla:");

        tbl_articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_articulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostarimg(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_articulos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_añadircarrito)
                                    .addComponent(btn_mostrarartiulos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spn_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(tf_talla)))
                    .addComponent(etiqueta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guardarpedido, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_actualizarcarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_añadircarrito))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mostrarartiulos)
                    .addComponent(btn_actualizarcarrito))
                .addGap(433, 433, 433))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrarartiulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarartiulosActionPerformed
        // TODO add your handling code here:
        Connection conexion=null;
        Statement st=null;
        ResultSet rs=null;
        
        conexion=conectar();
        try{
            st=conexion.createStatement();
            rs = st.executeQuery("SELECT nombre,descripcion,tipoarticulo,precio from articulo group by nombre");
            while (rs.next()){
                Object [] fila=new Object[4];
                fila[0]=rs.getObject(1);
                fila[1]=rs.getObject(2);
                fila[2]=rs.getObject(3);
                fila[3]=rs.getObject(4);
               dtm_articulo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try{
                st.close();
                conexion.close();
            } catch (SQLException ex) {
                Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
    }//GEN-LAST:event_btn_mostrarartiulosActionPerformed

    private void mostarimg(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostarimg
        // TODO add your handling code here:
//        String foto=null;
//        int i=tbl_articulos.getSelectedRow();
//        Articulo a=(Articulo)dtm_articulo.get(i);
//        foto=a.getFotografia();
//        ImageIcon img=new ImageIcon(foto);
//        JLabel etiqueta=new JLabel();
//        etiqueta.setIcon(img);
    }//GEN-LAST:event_mostarimg

    private void btn_añadircarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadircarritoActionPerformed
        // TODO add your handling code here:
        int i=tbl_articulos.getSelectedRow();
        
        String nombre=(String)dtm_articulo.getValueAt(i, 0);
        String tipo=(String)dtm_articulo.getValueAt(i, 2);
        int precio=(int)dtm_articulo.getValueAt(i, 3);
        
        if(tipo.equalsIgnoreCase("zapato")){
            int numero=Integer.parseInt(tf_talla.getText());
            Zapato z=new Zapato(numero,tipo,nombre,precio);
            dlm_carrito.addElement(z);
        }else{
            if(tipo.equalsIgnoreCase("bolso")){
                String tipo2=(String)dtm_articulo.getValueAt(i, 1);
                Bolso b=new Bolso(tipo2,nombre,precio);
                dlm_carrito.addElement(b);
            }else{
                int numero=Integer.parseInt(tf_talla.getText());
                String tipo3=(String)dtm_articulo.getValueAt(i, 1);
                Complemento c=new Complemento(numero,tipo3,nombre,precio);
                dlm_carrito.addElement(c);
            }
        }
        
        lst_carrito.setModel(dlm_carrito);
    }//GEN-LAST:event_btn_añadircarritoActionPerformed

    private void btn_guardarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarpedidoActionPerformed
        // TODO add your handling code here:
        Connection c=conectar();
        PreparedStatement ps=null;
        int res=0;
        
        try{
            ps=c.prepareStatement("INSERT INTO pedido (total) VALUES (?)");
//            ps.setString(1, tf_nombre.getText());
//            ps.setString(2, tf_direcc.getText());
//            ps.setString(3, tf_telf.getText());
            res=ps.executeUpdate();
            if(res>0){
                JOptionPane.showMessageDialog(null, "Pedido añadida correctamente");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR.No se añadio el pedido");
            }
        } catch (SQLException ex) {
            Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardarpedidoActionPerformed

    //metodo para conectar el drive
    public static Connection conectar(){
        Connection conexion=null;
        Statement st=null;
        ResultSet rs=null;
        //se puede hacer un metodo que devolveria un connection
        try{
            conexion =DriverManager.getConnection(URL,USERNAME, PASSWORD);

        }catch (SQLException ex) {
            Logger.getLogger(HacerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        return conexion;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HacerPedido dialog = new HacerPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarcarrito;
    private javax.swing.JButton btn_añadircarrito;
    private javax.swing.JButton btn_guardarpedido;
    private javax.swing.JButton btn_mostrarartiulos;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst_carrito;
    private javax.swing.JSpinner spn_cantidad;
    private javax.swing.JTable tbl_articulos;
    private javax.swing.JTextField tf_talla;
    // End of variables declaration//GEN-END:variables
}
