/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edt5y6tacondeoro;

import edt5tacondeoro1.Articulo;
import edt5tacondeoro1.Bolso;
import edt5tacondeoro1.Complemento;
import edt5tacondeoro1.LineaPedido;
import edt5tacondeoro1.Pedido;
import edt5tacondeoro1.Ruta;
import edt5tacondeoro1.Socio;
import edt5tacondeoro1.Zapato;
import java.util.ArrayList;

/**
 *
 * @author admin
 */
public class SistemaVP extends javax.swing.JFrame {
    ArrayList<Articulo> listaArticulos;
    ArrayList<Socio> listaSocios;
    ArrayList<Ruta> listaRutas;
    ArrayList<Pedido> listaPedidos;
    ArrayList<LineaPedido> listaLineasP;

    /**
     * Creates new form SistemaVP
     */
    public SistemaVP() {
        initComponents();
        listaArticulos= new <Articulo> ArrayList();
        listaSocios= new <Socio> ArrayList();
        listaRutas= new <Ruta> ArrayList();
        listaPedidos= new <Pedido> ArrayList();
        listaLineasP= new <LineaPedido> ArrayList();
        
    }
    public void crearDatosDePrueba(){
        LineaPedido lp=null;
        //Creamos dos socios: Máxmo hará un pedido desbordando el Stock y Prudencio hará pedido con suficiente stock
        Socio maxi= new Socio("Maximo","maximo@mail.com","C/ Locura, sn","Sevilla");
        Socio pruden= new Socio("Prudencio","prudencio@mail.com","C/ Esperanza, sn","Barcelona");
        listaSocios.add(maxi);
        listaSocios.add(pruden);
        //Creamos unos artículos de ejemplo: bolso zapatos y complemento.
        Bolso b= new Bolso("bandolera","NikeBolso",50,"Blanco, cómodo y flexible","cuero",10,"fotoBolso");
        Zapato z= new Zapato(38,"Deportivas","NikeZapato",200,"Blanco, cómodo y flexible","cuero",10,"fotoBolso");
        Complemento c= new Complemento("Cinturón",54,"NikeComplemento",25,"Blanco, cómodo y flexible","cuero",10,"fotoBolso");
        listaArticulos.add(b);
        listaArticulos.add(z);
        listaArticulos.add(c);
        //Creamos algunos Pedidos sin las líneas, ya que se las añadimos posteriormente
        Pedido pmaxi= new Pedido(maxi);
        Pedido ppruden= new Pedido(pruden);
        //Creamos algunas lineas de pedido
        lp= new LineaPedido (b,15);// bolso, 15 unidades. No hay stock.
        //Metemos esta lineaPedido en la listaLineasPedidos
        listaLineasP.add(lp);
        //Metemos esta lista de lineas de pedido en el pedido de Máximo:
        pmaxi.setLineasPedidos(listaLineasP);//Este pedido no se puede cumplimentar por falta de stock.
        //Ahora crearemos lineas de pedido con artículos con suficiente stock y lo meteremos en el pedido de pruden.
        listaLineasP.clear();//Limpiamos la lista de líneas para dejarla vacía y usarla para el otro pedido
        lp= new LineaPedido (b,5);// bolso, 5 unidades. Hay stock.
        listaLineasP.add(lp);
        lp= new LineaPedido (z,8);// zapato, 8 unidades. Hay stock.
        listaLineasP.add(lp);
        //Metemos esta lista de lineas de pedido en el pedido de Prudencio:
        ppruden.setLineasPedidos(listaLineasP);
        //Metemos los dos pedidos en la lista de pedidos
        listaPedidos.add(pmaxi);
        listaPedidos.add(ppruden);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_registrar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mn_iniciar = new javax.swing.JMenuItem();
        mn_tupedido = new javax.swing.JMenu();
        mn_hacerpedido = new javax.swing.JMenuItem();
        mn_estado = new javax.swing.JMenuItem();
        mn_cancelar = new javax.swing.JMenuItem();
        mn_cumplimentar = new javax.swing.JMenu();
        mn_cumplimentarpedido = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(382, 50));

        mn_registrar.setText("REGISTRATE");

        jMenuItem1.setText("Registrar");
        mn_registrar.add(jMenuItem1);

        mn_iniciar.setText("Iniciar Sesión");
        mn_registrar.add(mn_iniciar);

        jMenuBar1.add(mn_registrar);

        mn_tupedido.setText("HAZ TU PEDIDO");

        mn_hacerpedido.setText("Haz tu pedido");
        mn_hacerpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_hacerpedidoActionPerformed(evt);
            }
        });
        mn_tupedido.add(mn_hacerpedido);

        mn_estado.setText("Ver estado del pedido");
        mn_tupedido.add(mn_estado);

        mn_cancelar.setText("Cancelar pedido");
        mn_tupedido.add(mn_cancelar);

        jMenuBar1.add(mn_tupedido);

        mn_cumplimentar.setText("CUMPLIMENTAR PEDIDO");

        mn_cumplimentarpedido.setText("Cumplimentar");
        mn_cumplimentarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_cumplimentarpedidoActionPerformed(evt);
            }
        });
        mn_cumplimentar.add(mn_cumplimentarpedido);

        jMenuBar1.add(mn_cumplimentar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_hacerpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_hacerpedidoActionPerformed
        // TODO add your handling code here:
        HacerPedido pedido=new HacerPedido(this,true);
        pedido.setVisible(true);
    }//GEN-LAST:event_mn_hacerpedidoActionPerformed

    private void mn_cumplimentarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_cumplimentarpedidoActionPerformed
        // TODO add your handling code here:
        DCumplimentarPedido cumplimentar=new DCumplimentarPedido(this,true);
        cumplimentar.setVisible(true);
    }//GEN-LAST:event_mn_cumplimentarpedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaVP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mn_cancelar;
    private javax.swing.JMenu mn_cumplimentar;
    private javax.swing.JMenuItem mn_cumplimentarpedido;
    private javax.swing.JMenuItem mn_estado;
    private javax.swing.JMenuItem mn_hacerpedido;
    private javax.swing.JMenuItem mn_iniciar;
    private javax.swing.JMenu mn_registrar;
    private javax.swing.JMenu mn_tupedido;
    // End of variables declaration//GEN-END:variables
}
