/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edt5y6tacondeoro;

import edt5tacondeoro1.Articulo;
import edt5tacondeoro1.Bolso;
import edt5tacondeoro1.Complemento;
import edt5tacondeoro1.LineaPedido;
import edt5tacondeoro1.Pedido;
import edt5tacondeoro1.Ruta;
import edt5tacondeoro1.Socio;
import edt5tacondeoro1.Zapato;
import java.util.ArrayList;

/**
 *
 * @author admin
 */
public class SistemaVP extends javax.swing.JFrame {
    ArrayList<Articulo> listaArticulos;
    ArrayList<Socio> listaSocios;
    ArrayList<Ruta> listaRutas;
    ArrayList<Pedido> listaPedidos;
    ArrayList<LineaPedido> listaLineasP;

    /**
     * Creates new form SistemaVP
     */
    public SistemaVP() {
        initComponents();
        listaArticulos= new <Articulo> ArrayList();
        listaSocios= new <Socio> ArrayList();
        listaRutas= new <Ruta> ArrayList();
        listaPedidos= new <Pedido> ArrayList();
        listaLineasP= new <LineaPedido> ArrayList();
        
    }
    public void crearDatosDePrueba(){
        LineaPedido lp=null;
        //Creamos dos socios: Máxmo hará un pedido desbordando el Stock y Prudencio hará pedido con suficiente stock
        Socio maxi= new Socio("Maximo","maximo@mail.com","C/ Locura, sn","Sevilla");
        Socio pruden= new Socio("Prudencio","prudencio@mail.com","C/ Esperanza, sn","Barcelona");
        listaSocios.add(maxi);
        listaSocios.add(pruden);
        //Creamos unos artículos de ejemplo: bolso zapatos y complemento.
        Bolso b= new Bolso("bandolera","NikeBolso",50,"Blanco, cómodo y flexible","cuero",10,"fotoBolso");
        Zapato z= new Zapato(38,"Deportivas","NikeZapato",200,"Blanco, cómodo y flexible","cuero",10,"fotoBolso");
        Complemento c= new Complemento("Cinturón",54,"NikeComplemento",25,"Blanco, cómodo y flexible","cuero",10,"fotoBolso");
        listaArticulos.add(b);
        listaArticulos.add(z);
        listaArticulos.add(c);
        //Creamos algunos Pedidos sin las líneas, ya que se las añadimos posteriormente
        Pedido pmaxi= new Pedido(maxi);
        Pedido ppruden= new Pedido(pruden);
        //Creamos algunas lineas de pedido
        lp= new LineaPedido (b,15);// bolso, 15 unidades. No hay stock.
        //Metemos esta lineaPedido en la listaLineasPedidos
        listaLineasP.add(lp);
        //Metemos esta lista de lineas de pedido en el pedido de Máximo:
        pmaxi.setLineasPedidos(listaLineasP);//Este pedido no se puede cumplimentar por falta de stock.
        //Ahora crearemos lineas de pedido con artículos con suficiente stock y lo meteremos en el pedido de pruden.
        listaLineasP.clear();//Limpiamos la lista de líneas para dejarla vacía y usarla para el otro pedido
        lp= new LineaPedido (b,5);// bolso, 5 unidades. Hay stock.
        listaLineasP.add(lp);
        lp= new LineaPedido (z,8);// zapato, 8 unidades. Hay stock.
        listaLineasP.add(lp);
        //Metemos esta lista de lineas de pedido en el pedido de Prudencio:
        ppruden.setLineasPedidos(listaLineasP);
        //Metemos los dos pedidos en la lista de pedidos
        listaPedidos.add(pmaxi);
        listaPedidos.add(ppruden);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Hacer Pedido (Socio)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cumplimentar Pedido (responsable almacén)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(160, 160, 160))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HacerPedido pedido=new HacerPedido(this,true);
        pedido.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DCumplimentarPedido cumplimentar=new DCumplimentarPedido(this,true);
        cumplimentar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaVP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
